---
development:
  cloud_name: dbri1xgl8
  api_key: '214988934268252'
  api_secret: p6LfwxeL0P-B7i-QsblueKTDm5I
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dbri1xgl8
  api_key: '214988934268252'
  api_secret: p6LfwxeL0P-B7i-QsblueKTDm5I
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dbri1xgl8
  api_key: '214988934268252'
  api_secret: p6LfwxeL0P-B7i-QsblueKTDm5I
  enhance_image_tag: true
  static_image_support: false
